language: node_js

node_js:
  - "6.5"

services:
  - postgresql
  - redis-server

env:
  - CXX=g++-4.8 NODE_ENV=development DB_ENV=travis

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - unicode-data
  postgresql: "9.5"

before_script:
  - psql -c 'create database libertysoil;' -U postgres
script: "npm run travis"
