db:
  image: "postgres:9.4"
  ports:
    - "127.0.0.1:5432:5432"
  volumes:
    - "/mnt/data/postgres:/var/lib/postgresql/data"
  environment:
    - "POSTGRES_PASSWORD=Laik7akoh2ai"
  restart: always
redis:
  image: "redis:3.0"
  restart: always
app:
  image: "quay.io/dipstudio/libertysoil:1.2.1"
  ports:
    - "127.0.0.1:8000:8000"
  links:
    - db
    - redis
  environment:
    - "API_HOST=http://www.libertysoil.org"
    - "VIRTUAL_HOST=www.libertysoil.org,libertysoil.org"
    - "DB_ENV=staging"
  env_file:
    - "./secrets.env"
  restart: always
queue:
  image: "quay.io/dipstudio/libertysoil:1.2.1"
  links:
    - db
    - redis
  environment:
    - "API_HOST=http://www.libertysoil.org"
    - "DB_ENV=staging"
  env_file:
    - "./secrets.env"
  command: npm run tasks
  restart: always
web:
  image: "jwilder/nginx-proxy"
  ports:
    - "80:80"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
  restart: always
